name       : raylib
version    : 3.7.0
release    : 6
source     :
    - https://github.com/raysan5/raylib/archive/3.7.0.tar.gz : 7bfdf2e22f067f16dec62b9d1530186ddba63ec49dbd0ae6a8461b0367c23951
license    : zlib-acknowledgement
component  : programming.library
summary    : A simple and easy-to-use library to enjoy videogames programming
description: |
    raylib is highly inspired by Borland BGI graphics lib and by XNA framework and it's specially well suited for prototyping, tooling, graphical applications, embedded systems and education.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glfw3)
setup      : |
    %cmake_ninja \
        -DWITH_PIC=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DUSE_EXTERNAL_GLFW=ON \
        -DINCLUDE_EVERYTHING=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
