name       : raylib
version    : 3.0.0
release    : 3
source     :
    - https://github.com/raysan5/raylib/archive/3.0.0.tar.gz : 164d1cc1710bb8e711a495e84cc585681b30098948d67d482e11dc37d2054eab
license    : zlib-acknowledgement
component  : programming.library
summary    : A simple and easy-to-use library to enjoy videogames programming
description: |
    raylib is highly inspired by Borland BGI graphics lib and by XNA framework and it's specially well suited for prototyping, tooling, graphical applications, embedded systems and education.
builddeps  :
    - pkgconfig(glfw3)
    - pkgconfig(gl)
setup      : |
    %cmake_ninja \
        -DSHARED=ON \
        -DSTATIC=OFF \
        -DWITH_PIC=ON \
        -DUSE_EXTERNAL_GLFW=ON \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_GAMES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
