name       : raylib
version    : 4.5.0
release    : 9
source     :
    - https://github.com/raysan5/raylib/archive/refs/tags/4.5.0.tar.gz : 0df98bfc553db31356cab46a2f9ed6d932065f186a0fff24bafa05f8a60e16d1
homepage   : https://www.raylib.com/
license    : zlib-acknowledgement
component  : programming.library
summary    : A simple and easy-to-use library to enjoy videogames programming
description: |
    raylib is highly inspired by Borland BGI graphics lib and by XNA framework and it's specially well suited for prototyping, tooling, graphical applications, embedded systems and education.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glfw3)
setup      : |
    %cmake_ninja \
        -DWITH_PIC=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DUSE_EXTERNAL_GLFW=ON \
        -DINCLUDE_EVERYTHING=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
